run:
  tests: false
linters:
  enable-all: true
  disable:
    - dupl
    - funlen
    - gochecknoglobals
    - lll
    - scopelint
    - godot
    - paralleltest
    - exhaustivestruct
    - ifshort
    - nestif
    - varnamelen
    - ireturn
    - golint
    - interfacer
    - scopelint
    - maligned
    - cyclop
    - tagliatelle
linters-settings:
  govet:
    check-shadowing: true
  maligned:
    suggest-new: true
  misspell:
    locale: US
  goerr113:
    ignore-tests: true